### ISSUE TITLE
Error when saving changes to Data Collectors

### ISSUE THREAD

**Issue by hmorandell** [Cacti/cacti#2273]
Hi,
when I save changes to the main Data Collectors, I get this warning and error in the logfile:

```
2019/01/05 14:35:35 - CMDPHP PHP ERROR NOTICE Backtrace: (/pollers.php[217]:form_save(), /pollers.php[290]:CactiErrorHandler())
--
2019/01/05 14:35:35 - ERROR PHP NOTICE: Undefined index: dbhost in file: /var/www/html/pollers.php on line: 290
```

the changes are saved, just wanted to let you now maybe this one should be fixed.

**Comment by cigamit** [comment]
This is indicative of a bad upgrade.  That column was added in 1.0, your database permissions may be blocking you from dropping a table, and that may have caused this.  The default database permissions required by the Cacti installer are `GRANT ALL`, though some administrators try to lock things down.  In the 1.0 upgrade, we drop the poller table and re-create it.  If you are running multiple data collectors, you might want to manually add the column in, otherwise, you can run the following from the cli:

`php -q upgrade_database.php --forcever=0.8.8h`

That should add that column as expected.

**Comment by hmorandell** [comment]
strange - I executed this statement now but I had a clean install before/ I upgraded before from 0.8.8 to 1.2.0 beta 4.
My poller table looks like this

```
           id: 1
     disabled:
         name: Main Poller
        notes:
       status: 2
     timezone: Europe/Moscow
     hostname: bvpcactihd
    dbdefault: cacti
       dbhost: bvpcactihd
       dbuser:
       dbpass:
       dbport: 3306
        dbssl:
      dbsslca: NULL
    dbsslcert: NULL
     dbsslkey: NULL
   total_time: 36.2914
     max_time: 48.312108039856
     min_time: 32.463814020157
     avg_time: 35.66421884795
  total_polls: 48
    processes: 2
      threads: 20
sync_interval: 7200
         snmp: 29064
       script: 226
       server: 5
  last_update: 2019-01-08 19:59:38
  last_status: 2019-01-08 19:59:38
    last_sync: 0000-00-00 00:00:00
```
when I change values and save the Data Collector, the error still remains.... Any idea?
