### ISSUE TITLE
Issue in Reporting when adding graph

### ISSUE THREAD

**Issue by hmorandell** [Cacti/cacti#2295]
Hello,
when I create a report and add graphs on it, there seems that the local_graph_id is somehow not passed on, as in the database I always get value of 0 and in the preview tab I get a "Unknow RRDTool Errore"

This is how a inserted record looks like:

```
MariaDB [cacti]> select * from reports_items WHERE id=123\G;
*************************** 1. row ***************************
               id: 123
        report_id: 20
        item_type: 1
          tree_id: 0
        branch_id: 0
     tree_cascade:
graph_name_regexp:
 host_template_id: 8
          host_id: 9042
graph_template_id: 145
   local_graph_id: 0
         timespan: 7
            align: 1
        item_text:
        font_size: 16
         sequence: 2
1 row in set (0.00 sec)

```

when I update the local_graph_id manually the graph is correct and the report works:

```
MariaDB [cacti]> select * from reports_items WHERE id=121\G;
*************************** 1. row ***************************
               id: 121
        report_id: 20
        item_type: 1
          tree_id: 0
        branch_id: 0
     tree_cascade:
graph_name_regexp:
 host_template_id: 8
          host_id: 9042
graph_template_id: 175
   local_graph_id: 49085
         timespan: 6
            align: 1
        item_text:
        font_size: 16
         sequence: 1
1 row in set (0.00 sec)

```

I tried to have a look in lib/reports.php and the function which adds the item seems to be reports_add_graphs, but it look alright to me.
