### ISSUE TITLE
Graph/Data Source creation with custom fields not prompting during 1st creation

### ISSUE THREAD

**Issue by AllenRDCo** [Cacti/cacti#3879]
When adding a new device and doing the initial creating of graphs/data sources for the device if there are any data sources that have custom fields (such as network traffic has a custom field for the interface to monitor) the previous behavior was after the device has been added those graphs would not auto create if graph auto creation was enabled and you would have to follow the "Create Graphs for this device" link and then select the graphs, then click the "Create Graphs" button and you would then be taken to the next page to enter the custom fields (interface, drive, etc) and then you could finalize the graph/data source creation. 

Now the behavior, whether or not you have automatic graph creation enabled or not, is upon the initial creation of graphs it will not prompt for the custom fields, resulting in data sources without required fields (such as the interface to monitor) resulting in broken graphs. You then have to go into each data source and manually update the data source with the missing information before it starts working again. The additional behavior of this is that when you have graphs/data sources that are configured to allow more than one instance for a single device, if you create the second instance of that graph for the device it does prompt for the custom fields as one would expect. So it is only a problem upon the first creation of those graphs/data sources. I checked through all the settings I could find (none of which were changed before the behavior started) and nothing seemed to address the problem. I also looked at the individual data source templates to make sure nothing was set wrong in them and could not find anything. Granted, the templates I am using in this manner are sourced from Percona, but this is the first time I have had this kind of issue and it seems unlikely it is a problem with the templates, though it might be.

This appears to have changed between 1.2.12 and 1.2.14.

This is on a Debian 10 system that is up to date and running php7.3 with Percona MySQL 5.7.31

**Comment by TheWitness** [comment]
Well that's a good catch.  Not sure what caused it, but thanks for reporting.  Won't take to long to fix.

**Comment by TheWitness** [comment]
I've just verified that is does work.  What you should do is disable Automatic Graph Creation under Console > Configuration > Settings > General.  Currently, when Automatic Graph Creation is enabled, the 'defaults' are take for custom Data Sources.

**Comment by AllenRDCo** [comment]
I did disable automatic graph creation though as mentioned in my initial report. Even with automatic graph creation disabled and manually creating all the graphs after saving the device, the first time graphs with custom values in the data sources are created it will not prompt for them and still creates them with empty values. If you then create a second set of the same graphs on the same device it will prompt you.

Either way, the behavior originally was to prompt for the values, regardless of automatic graph creation being enabled or not.

**Comment by AllenRDCo** [comment]
It seems to me that when something is working as expected in a previous version but suddenly and unintentionally stops working in a new version that qualifies it as a bug, even if there is supposedly a work around for it (which again, that work around did _not_ work for me).

**Comment by TheWitness** [comment]
Turn off graph automation, and it'll work exactly as before.

**Comment by AllenRDCo** [comment]
@TheWitness As I have mentioned a few times now, disabling automatic graph creation has not made any difference for me. Even with it disabled I still have this bug where the first time the graphs are created it does not prompt for the custom fields and instead creates the graphs with empty fields. Only upon the second time the graphs are created will it prompt. I did a screencapture demonstrating this for you since my words seem to be failing to convey the message: https://youtu.be/X2U7Io-PNAw

**Comment by TheWitness** [comment]
So Paul, when you edit the Data Template, is the checkbox to allow you to override the default value checked?  Verify for your Data Templates, and upload images of them.

Also, for one of the problem Data Templates, that you have confirmed that the checkbox es are checked, send the output of:

```sql
SELECT * FROM data_template_data WHERE data_template_id = X AND local_data_id = 0\G
```

**Comment by AllenRDCo** [comment]
@TheWitness 
Yes, the option for override default value is selected in the affected data sources, as it always has been for our setup:
![image](https://user-images.githubusercontent.com/7156488/101091854-fdc62880-3575-11eb-8847-9576c42aed2f.png)

```
mysql> SELECT *  FROM data_template_data  WHERE data_template_id = 122  AND local_data_id = 0\G
*************************** 1. row ***************************
                         id: 122
local_data_template_data_id: 0
              local_data_id: 0
           data_template_id: 122
              data_input_id: 52
                     t_name: on
                       name: |host_description| - Disk Space
                 name_cache: 
           data_source_path: 
                   t_active: 
                     active: on
                 t_rrd_step: 
                   rrd_step: 60
   t_data_source_profile_id: 
     data_source_profile_id: 4
1 row in set (0.00 sec)
```


![image](https://user-images.githubusercontent.com/7156488/101091944-1c2c2400-3576-11eb-853c-097461425ff0.png)

```
mysql> SELECT *  FROM data_template_data  WHERE data_template_id = 123  AND local_data_id = 0\G
*************************** 1. row ***************************
                         id: 123
local_data_template_data_id: 0
              local_data_id: 0
           data_template_id: 123
              data_input_id: 53
                     t_name: on
                       name: |host_description| - Network Traffic
                 name_cache: 
           data_source_path: 
                   t_active: 
                     active: on
                 t_rrd_step: 
                   rrd_step: 60
   t_data_source_profile_id: 
     data_source_profile_id: 4
1 row in set (0.00 sec)
```

BTW, I am upgraded to cacti 1.2.15 now and still having this issue. Automatic graph creation is still disabled.
