### ISSUE TITLE
[1.2.20] - Unix ping template not passing hostname to arg1 in poller_item

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/cacti#4699]
Hey All,

I am seeing that for the UNIX ping and Advanced ping template  that the hostname is not present in the poller_item table 
causing nan in the graphs

```
*************************** 35. row ***************************
       local_data_id: 218
           poller_id: 1
             host_id: 109
              action: 1
             present: 1
        last_updated: 2022-04-12 12:09:42
            hostname: 192.168.1.197
      snmp_community: private
        snmp_version: 2
       snmp_username:
       snmp_password:
  snmp_auth_protocol:
snmp_priv_passphrase:
  snmp_priv_protocol:
        snmp_context:
      snmp_engine_id:
           snmp_port: 161
        snmp_timeout: 500
            rrd_name: ping
            rrd_path: /var/www/html/cacti/rra/192_168_1_197_ping_218.rrd
             rrd_num: 1
            rrd_step: 60
       rrd_next_step: 0
                arg1: perl /var/www/html/cacti/scripts/ping.pl '' <<
                arg2:
                arg3:
35 rows in set (0.001 sec)
```

Rebuilding poller_cache does not correct the issue
If you manually update the arg1 field with the IP the graphs start to work again

I am not sure if this is related to the issue of the corrupted packages
This is on my test bed using the latest 1.2.x commits as of 20 minutes ago
